Tencent/TSW

- .gitignore
- .travis.yml
- bin/tsw/util/Queue/index.js
- package.json
1. 增加coveralls 支持
2. ignore相关覆盖率结果文件
3. travis只执行node 9，并增加目录缓存
4. 解决eslint报错
> 接入coveralls自动测试代码覆盖率

- .npmrc
- package.json
如果选择信赖第三方库，不予锁定版本，那么增加`.npmrc`配置文件，避免`npm install`的时候产生`package-lock.json`文件
关于`package-lock.json`的[讨论](https://www.zhihu.com/question/264560841)
避免这个WARN
> chore: add .npmrc to avoid making package-lock.json

- bin/tsw/loader/seajs/lib/sea-node.js
avoid problems in v8.9.0 require.resolve case
**Checklist:**
```js
"use strict";
console.time(1);
for(var i = 0; i < 100000; i++){
require('./require.cpu.empty.js');
}
const a = require.resolve('./require.cpu.empty.js', {paths: []}) // 这里正常会报错
console.timeEnd(1);
var Module = module.constructor;
var _resolveFilename = Module._resolveFilename
Module._resolveFilename = function(request, parent) {
var res;
//性能优化
if(parent.resolveFilenameCache){
if(parent.resolveFilenameCache[request]){
return parent.resolveFilenameCache[request]
}
}else{
parent.resolveFilenameCache = {};
}
res = _resolveFilename(request, parent, isMain, options);
parent.resolveFilenameCache[request] = res;
return res;
}
console.time('2');
for(var i = 0; i < 100000; i++){
require('./require.cpu.empty.js');
}
const b = …
```
> fix(sea-node): do not use cache when `options` has `paths` property

- conf/config.js
**Checklist:**
- [ * ] test cases has added or updated
- [ * ] documentation has added or updated
- [ * ] commit message follows the [convention commit guidelines](https://conventionalcommits.org/)
TSW的配置文件支持在启用的时候传入参数
例如在诸如WebStorm、Visual Studio Code中就可以这样配置，以实现选择不同的项目调试：
```json
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "TSW(photo.v7)",
"program": "${workspaceFolder}/TSW/index.js",
"args": [
"config=../../photo.v7/nodejs/server/conf/dev/config.js"
]
},
{
"type": "node",
"request": "launch",
"name": "TSW(git-hook)",
"program": "${workspaceFolder}/TSW/index.js",
"args": [
"config=../../git-hook/config.js"
]
}
]
}
```
> 允许在启动参数中指定config文件的路径

- bin/tsw/pool/cmem.l5.js
>  fix(cmem.l5): use instances cache instead of poolsize

- bin/proxy/http.proxy.js
- bin/proxy/websocket.js
> feat(websocket): optimize report log

- bin/proxy/websocket.js
> fix(websocket): log message length instead of message body

- bin/tsw/runtime/overloadProtection.js
when random num between 0 to rejectRate, reject it
**Checklist:**
> fix: rejecting condition of overloadProtection

- bin/proxy/config.js
在读取全局配置文件的时候，增加对环境变量`TSW_CONFIG_PATH`，如果有此环境变量，那么会读取这个变量的值当做配置文件的地址
**Checklist:**
> feat: add TSW_CONFIG_PATH env

- Dockerfile
**Checklist:**
alpine linux上的nodejs已经不再包含nodejs-npm，需要解决创建docker image时出现错误。
> chore(docker): add nodejs-npm for building image

- bin/proxy/master.js
- bin/tsw/util/logger/logger.config.js
- bin/tsw/util/logger/logger.js
**Checklist:**
用判断启动参数是否包含`inspect`来判断当前是否处于调试模式，以兼容Node 12移除`process.binding('config').debugOptions`后无法判断这一模式的问题。
> fix: resolved Tencent/TSW#317

- bin/proxy/master.js
- bin/tsw/default/config.default.js
**Checklist:**
在配置文件中增加`ignoreSIGTERM`属性。如果它的值为true，在TSW主进程运行过程中会忽略来自系统的`SIGTERM`信号。在kubernetes中可以配合`terminationGracePeriodSeconds`属性使用。
> feat: add ignoreSIGTERM config

- bin/tsw/loader/seajs/lib/sea-node.js
**Checklist:**
由于node源码对loader.js的[改动](https://github.com/nodejs/node/commit/a608caa5ffb428994c4f508b426d25dae2dbda54)，在调用`_resolveFilename`时`options`传入一个空对象`{}`会导致在判断条件时出现错误。为了解决这个问题在hack `_resolveFilename`方法的时候需要做到不变更`options`的值。
> fix: 修复node 12.4.0以后require相对上级目录无法找到模块的问题

- lib/index.ts
**Checklist:**
```javascript
installHacks();
await import(path.resolve(basePath, mainPath));
uninstallHacks();
```
在 lib/index.ts中,由于await import文件中,再次hacks了console对象。由于是异步事件，当uninstallHacks()执行之后，console对象不存在originxx的属性方法。
```javascript
console.info = (
message?: any,
...optionalParams: any[]
): void => {
if (getCurrentContext() === null) {
return console.originInfo(message, ...optionalParams);
}
return logger.writeLog(
"INFO",
`${util.format(message, ...optionalParams)}`
);
};
```
这个时候,await语句中存在的异步事件调用hacks之后的console.info。由于console对象已经删除originInfo,所以报错。因此，需要去掉uninstallHacks()。
> fix: remove uninstallHacks

- benchmark/package-lock.json
- benchmark/package.json
- benchmark/start/tswconfig.js
- lib/core/logger/index.ts
- lib/core/runtime/capture/index.ts
- lib/core/runtime/dns.hack.ts
- lib/index.ts
- typings/type.d.ts
> feat: add cleanLog in tswconfig.js to hide default logs

- .eslintignore
> chore: ignore node_modules in eslint

- lib/core/logger/__test__/index.test.ts
> test(logger): add test unit for CleanLog

- benchmark/start/tswconfig.js
- lib/core/logger/index.ts
- lib/index.ts
- typings/type.d.ts
> feat(tswconfig): add logLevel in tswconfig.js

- lib/core/runtime/create-server.hack.ts
"nodejs里面EventEmitter初始化的时候，都会把当前的domain存下来。然后tsw里面又把整个请求的抓包存在domain.currentContext. 而数据库的PoolConnection类型又是继承EventEmitter的，Connection会一直存在，所以内存里就会一直有最初启动的几条流水线日志抓包。"
> fix(domain): 清理domain的时候，移除挂载在domain的context

- lib/core/runtime/create-server.hack.ts
> fix(context): req记录context，防止close和finish事件清理后无法上报

- lib/core/runtime/capture/incoming.ts
- lib/core/runtime/capture/outgoing.ts
- lib/core/runtime/create-server.hack.ts
> fix(incoming): 到达最大限制后，不再记录回包内容

- lib/__test__/index.test.ts
- lib/core/runtime/capture/__test__/incoming.test.ts
- lib/core/runtime/capture/incoming.ts
> fix(incoming): 解决存量缓冲内容读取失败问题
