bin/lib/util/isProbe.js
bin/proxy/http.proxy.js

chore(http): probe request

---

bin/proxy/admin.actions.js
bin/proxy/admin.js

chore(master): admin

---

bin/proxy/admin.actions.js
bin/proxy/admin.js
bin/tsw/ajax/ajax.js

chore(runtime): ajax-parse-error

---

bin/lib/default/config.default.js

chore(config): default-cpuLimit

---

.github/CODE_OF_CONDUCT.md
.github/PULL_REQUEST_TEMPLATE.md

- .github/PULL_REQUEST_TEMPLATE.md
- .github/CODE_OF_CONDUCT,md

add pull template & code conduct

---

.eslintignore

eslint ignore wwwroot

---

bin/proxy/master.js
bin/tsw/util/logger/logger.js

Dev to master

---

bin/proxy/http.proxy.js
bin/proxy/http.route.js

refactor http.proxy & http.route

---

bin/tsw/context.js
bin/tsw/runtime/Window.js
bin/tsw/util/cpu.js

move Window.windowHasDisabled to global

---

bin/proxy/master.js
bin/proxy/so.sh
bin/proxy/startup.sh

update startup shell

---

bin/lib/api/notify/index.js
bin/lib/util/mail/mail.js
bin/lib/util/mail/src/mail.tmpl.html
bin/lib/util/mail/tmpl.js
bin/proxy/http.proxy.js
bin/proxy/http.route.js
bin/proxy/master.js
bin/tsw/ajax/ajax.js
bin/tsw/runtime/CCFinder.js

style(all): use camelCase only

---

bin/proxy/http.proxy.js
bin/proxy/master.js

chore(master): inspect startup move to master

---

bin/proxy/admin.js
bin/proxy/master.js

refactor(master): master.js Readability optimization

---

bin/tsw/util/auto-report/TEReport.js

chore(h5test): groups sort before filter

---

bin/lib/default/config.default.js
bin/tsw/context.js
bin/tsw/runtime/CCFinder.js
bin/tsw/util/auto-report/TEReport.js

chore(ccfinder): support config.CCIPLimitAutoBlock

---

.eslintignore
bin/tsw/runtime/CCFinder.js

fix(ccfinder): update mail text

---

bin/proxy/so.sh

chore(shell): use execPath in startup.sh

---

bin/proxy/master.js

chore(n-api): ignore N-API warning mail

---

bin/proxy/admin.actions.js
bin/proxy/dump.heap.sh
bin/proxy/http.proxy.js
bin/proxy/http.route.js
bin/tsw/util/auto-report/alpha.js
bin/tsw/util/auto-report/logReport.js
bin/tsw/util/http.js
bin/tsw/util/http/parseGet.js
examples/skyMode/config.js
package.json

删除heapdump，抓包优化

---

bin/tsw/util/logger/callInfo.js

chore(logger): getCallInfo module improving performance

---

bin/tsw/runtime/CCFinder.js
examples/framework/.gitignore

 fix(ccfinder): init data start after clear

---

bin/tsw/runtime/capturer.js
bin/tsw/util/auto-report/download.js
bin/tsw/util/auto-report/logReport.js

refactor(capturer): support binary request body

---

bin/proxy/http.route.js
bin/proxy/websocket.js
bin/proxy/ws.route.js
bin/tsw/util/auto-report/logReport.js
bin/tsw/util/logger/logger.js

refactor(websocket): domain wrap websocket connection to end and websocket log stream report

---

bin/tsw/util/mail/src/mail.tmpl.html
bin/tsw/util/mail/tmpl.js

chore(mail): update mail tmpl

---

bin/proxy/admin.actions.js

fix(reload): ignore warning while reloading

---

bin/tsw/ajax/ajax.js
bin/tsw/runtime/capturer.js
bin/tsw/util/auto-report/download.js

抓包功能支持DNS信息

---

bin/tsw/ajax/ajax.js
bin/tsw/runtime/capturer.js

fix(capture): fix event leek

---

bin/proxy/websocket.js
bin/tsw/ajax/ajax.js
bin/tsw/api/tnm2/index.js
bin/tsw/runtime/capturer.js

refactor(ajax): listen socket error events

---

bin/tsw/runtime/Window.js

chore(window): support vue ssr

---

bin/tsw/util/openapi.js
test/bin/tsw/util/openapi.js

fix(openapi): filter key with undefined-value in sig calculation  RobinzZH committed

---

bin/proxy/websocket.js
bin/tsw/util/auto-report/logReport.js

fix(websocket): fix websocket log reportLogIndex

---

bin/tsw/util/auto-report/src/view.tmpl.html
bin/tsw/util/auto-report/tmpl.js

chore(logview): triple-clicking to highlight url

---

bin/tsw/runtime/Window.js

chore(window): revert support vue ssr

---

bin/proxy/master.js
bin/proxy/startup.sh

support for node-v10.5.0

---

bin/tsw/ajax/ajax.js
bin/tsw/runtime/Dns.hack.js
bin/tsw/runtime/capturer.js

fix(ajax): error events remove before close bug fix

---

bin/tsw/ajax/ajax.js
bin/tsw/loader/seajs/lib/sea-node.js

fix(ajax): do something for pipe on error

---

.eslintrc.json

chore(jslint): update jslint rules for tmpl.js

---

bin/tsw/util/http.js

fix(capture): push method instead of on-data event to capture

---

bin/tsw/runtime/capturer.js
bin/tsw/util/http.js

fix(capture): http.request capture on-data => push

---

.eslintrc.json

chore(jslint): close new-cap

---

.eslintrc.json

chore(jslint): update rules

---

bin/proxy/http.route.js
bin/tsw/util/auto-report/logReport.js

(cherry picked from commit eb891379753abd89c2a16a302814e0cf9703861f)
**Checklist:**

fix(coverity): fix errors in coverity report

---

bin/tsw/util/network.js

fix(network): bugfix for use address instead of tmp

---

bin/tsw/util/http.js

fix(captrue): must return the push result

---

.travis.yml
bin/proxy/http.route.js
bin/tsw/ajax/ajax.js
bin/tsw/runtime/capturer.js

 chore(router): string type limited for router.name

---

bin/proxy/http.proxy.js
bin/proxy/master.js
bin/tsw/runtime/overloadProtection.js
bin/tsw/util/cpu.js

Dev merge to TSW

---

bin/tsw/util/logger/callInfo.js

chore(logger): no use strict

---

bin/tsw/util/h5-test/is-test.js

fix(h5test): deal with res headersSent after fail

---

bin/proxy/websocket.js

fix(websocket): fix websocket not opened

---

package.json

(cherry picked from commit 31e511c76f6363d781737efc6d7f02d5bed471db)
**Checklist:**

feat(package.json): update package.json for R1.1.6

---

bin/proxy/http.route.js

chore(http): ignore errors after a stream was destroyed

---

bin/tsw/runtime/fs.hack.js

fix(runtime): bugfix for find bad code

---

bin/tsw/util/auto-report/logReport.js

fix(logreport): fixbug for logText assert

---

bin/tsw/runtime/CCFinder.js

chore(runtime): add a doc link in CCFinder mail

---

bin/proxy/http.proxy.js
bin/tsw/api/keyman/runtimeType.json

chore(runtime): add new runtime type 'CPU alert'

---

bin/tsw/util/auto-report/alpha.js

chore(alpha): move require to function

---

bin/proxy/master.js
bin/tsw/api/keyman/runtimeType.json

chore(runtime): add Memory over load alert

---

bin/tsw/runtime/CCFinder.js

fix(runtime): let url string instead of Tag a

---

bin/tsw/util/auto-report/logReport.js
bin/tsw/util/logger/logger.js

fix(websocket log): clear logJson

---

CONTRIBUTING.md

add CONTRIBUTING.md （#28）

---

bin/tsw/util/auto-report/logReport.js

fix(logreport): fixbug logText --> logJson

---

bin/proxy/admin.actions.js
bin/proxy/dump.heap.sh
bin/proxy/http.proxy.js
package.json

chore(heapdump): add heapdump

---

bin/proxy/webSocketServer.js

fix(websocket): check origin host bugfix

---

bin/tsw/util/auto-report/logReport.js

fix(logReport): clear logJson

---

bin/proxy/http.route.js
bin/tsw/runtime/ContextWrap.js

fix(contextwrap): remove window and context while ContextWrap.destory()

---

bin/proxy/webSocketServer.js

fix(websocket): default allow origin

---

bin/proxy/http.proxy.js

**Checklist:**
**Changelist:**
- rename variable, from `user_00` to `workerUid`

fix(httpproxy): rename variable user_00 -> workerUid

---

README.md
README_en.md
index.js
package.json

feat(npm): support npm and npx

---

changeLog.md

docs(changelog): update change log

---

bin/proxy/websocket.js

fix(websocket): bugfix

---

bin/proxy/kill.sh
bin/proxy/master.js

chore(master): keep process.title as TSW

---

bin/tsw/api/tnm2/index.js

chore(tnm2): async while reporting

---

bin/tsw/util/logger/logger.js

chore(logger): write once

---

bin/proxy/http.proxy.js
bin/proxy/http.route.js
bin/proxy/master.js
bin/proxy/websocket.js
bin/tsw/ajax/ajax.js
bin/tsw/i18n/lang.js
bin/tsw/runtime/CCFinder.js
locales/cn.json
locales/en.json
package.json

feat(i18n): support i18n

---

bin/tsw/api/tnm2/index.js
bin/tsw/default/config.default.js
bin/tsw/runtime/CCFinder.js

 chore(ccfinder): refactor ccfinder

---

bin/proxy/config.js

feat(config): add search path of config file

---

bin/tsw/runtime/CCFinder.js

fix(ccfinder): fix bug for miss end tag

---

bin/proxy/http.proxy.js
bin/tsw/runtime/CCFinder.js

fix(lang): fix translate error

---

bin/tsw/ajax/ajax.js

fix(ajax): assert null of request before use

---

bin/tsw/runtime/CCFinder.js
bin/tsw/util/http.isInnerIP.js
bin/tsw/util/http.js

feat(http): support ipv6

---

bin/proxy/config.js

fix(config): use resolve support absolute path & fix require

---

changeLog.md

docs(changelog): append changelog for 1.2.2

---

bin/tsw/default/config.default.js

chore(config): support ipv6 as default

---

bin/tsw/util/auto-report/download.js

fix(download): compatibility with uppercase & lowercase header

---

bin/tsw/pool/cmem.l5.js

fix(cmem): fix socket shutdown but still in the pool

---

bin/tsw/pool/cmem.l5.js

fix(cmem): reduce cmem client retry and reconnect time

---

bin/proxy/admin.js
bin/tsw/default/config.default.js

feat(config): add config.httpAdminAddress

---

bin/tsw/util/auto-report/download.js

feat(config): modify download.js

---

bin/tsw/ajax/ajax.js

chore(ajax): use httpProxy global instead of only devMode

---

bin/proxy/websocket.js
bin/tsw/pool/cmem.l5.js

fix(cmem): modified cmem option and added websocket log

---

bin/tsw/ajax/ajax.js
bin/tsw/runtime/capturer.js

chore(capture): delete response.close event listening

---

bin/tsw/api/logman/index.js

refactor(logman): use async api instead of sync

---

bin/tsw/runtime/CCFinder.js

fix(ccfinder): fix IDENTICAL_BRANCHES

---

bin/tsw/default/config.default.js

chore(config): update default value of memoryLimit

---

bin/tsw/api/logman/index.js

refactor(logman): logDir now can configure

---

bin/proxy/http.route.js

fix(router): let it going while response closing

---

bin/tsw/api/logman/index.js

fix(logman): fix bug for fs status

---

bin/tsw/ajax/ajax.js

chore(ajax): add default user-agent for ajax

---

test/bin/tsw/util/h5-test/api.test.js

fix(test): fix bug for tester

---

bin/proxy/websocket.js
bin/tsw/util/auto-report/alpha.js
test/bin/tsw/util/alpha.test.js

feat: add a function to judege a uin is alpha or not

---

bin/tsw/ajax/ajax.js
test/bin/config.js

chore(ajax): revert default ua for ajax

---

bin/proxy/websocket.js
bin/proxy/ws.route.js

feat: pass websocket server as a function param to the handler

---

bin/tsw/util/auto-report/download.js

fix(har): fix bug for hardata

---

bin/proxy/http.route.js
bin/proxy/so.sh
bin/tsw/runtime/CCFinder.js

chore(ccfinder): add min sum to deny block

---

bin/tsw/util/auto-report/TEReport.js

fix(h5test): add port in deduplication for testenv

---

bin/proxy/config.js
bin/proxy/master.js

chore(master): log configFrom on startup

---

bin/proxy/admin.js
bin/proxy/config.js
bin/proxy/http.origin.js
bin/proxy/http.proxy.js
bin/proxy/http.route.js
bin/proxy/master.js
bin/proxy/so.sh
bin/proxy/webSocketServer.js
bin/proxy/websocket.js
bin/proxy/ws.route.js
bin/tsw/ajax/ajax.js
bin/tsw/api/logman/index.js
bin/tsw/default/config.default.js
bin/tsw/pool/cmem.l5.js
bin/tsw/runtime/CCFinder.js
bin/tsw/runtime/capturer.js
bin/tsw/runtime/overloadProtection.js
bin/tsw/util/auto-report/TEReport.js
bin/tsw/util/auto-report/alpha.js
bin/tsw/util/auto-report/download.js
bin/tsw/util/auto-report/src/view.tmpl.html
bin/tsw/util/auto-report/tmpl.js
bin/tsw/util/cache.cleaner.js
changeLog.md
package.json
test/bin/config.js
test/bin/tsw/util/alpha.test.js
test/bin/tsw/util/h5-test/api.test.js

Release 1.2.3

---

bin/proxy/http.proxy.js
bin/proxy/master.js

fix(master): do not close self

---

examples/framework/package-lock.json

Update `package-lock.json` of example folder and fix a potential security vulnerability.
**Checklist:**

fix(config): update dependencies and fix a potential security vulnerability

---

bin/tsw/api/logman/index.js
bin/tsw/default/config.default.js
bin/tsw/runtime/CCFinder.js

feat(ccfinder): add CCIPLimitQuiet options to close notify

---

bin/tsw/util/http.js

chore(util): use realIp first

---

bin/proxy/http.proxy.js
bin/tsw/default/config.default.js
bin/tsw/runtime/overloadProtection.js

chore(master): update overload rules

---

bin/proxy/config.js

feat(config): support /data/release/tsw.config.js config path

---

bin/tsw/api/logman/index.js

feat(logman): add stop funciton for stopping

---

package.json

feat(changelogs): add script for changelog

---

bin/proxy/admin.js
bin/proxy/http.proxy.js
bin/proxy/kill.sh
bin/proxy/master-monitor.js
bin/proxy/master.js
bin/proxy/websocket.js

chore(server): exit while listening failure

---

bin/tsw/config.js

fix(config): resovle circular dependency

---

bin/proxy/http.proxy.js
bin/tsw/default/config.default.js

feat: use `devMode` and `autoCleanCache` to handle cache cleaning

---

bin/tsw/util/auto-report/alpha.js
bin/tsw/util/auto-report/encryption.js
bin/tsw/util/auto-report/logReport.js
bin/tsw/util/auto-report/post.js
bin/tsw/util/cache.cleaner.js
test/bin/tsw/util/auto-report/encryption.js

fix(encryption): upgrading des to aes for #304

---

bin/proxy/websocket.js

fix(websocket): window not find

---

package.json

fix: upgrade ws version to 7

---

bin/proxy/http.proxy.js
bin/proxy/http.route.js
bin/proxy/master.js
bin/proxy/ws.route.js
bin/tsw/ajax/ajax.js
bin/tsw/api/fileCache/index.js
bin/tsw/runtime/capturer.js
bin/tsw/util/auto-report/logReport.js
bin/tsw/util/http.js

fix: get user IP from XXF first

---

Dockerfile

chore: fix Dockerfile

---

bin/proxy/websocket.js

fix(websocket): fix websocket url not defined error

---

bin/tsw/default/config.default.js

fix(default): add websocket router, fixed #340

---

bin/proxy/http.route.js
bin/tsw/ajax/ajax.js
bin/tsw/util/http/parseBody.js

fix(ajax): fix bug for body is empty on delete request

---

.github/workflows/lint-and-test-code.yml
.github/workflows/publish-to-npm-alpha.yml
.releaserc.json
README.md
package.json

**Checklist:**
- 使用Github Actions替换travis
- 使用Github Actions完成自动发布npm

feat: add actions to publish npm automatically

---

bin/proxy/websocket.js

fix: set protocol proxy error

---

.github/workflows/lint-and-test-code.yml
.github/workflows/publish-to-npm-alpha.yml
.releaserc.json
bin/proxy/http.route.js
bin/tsw/util/http/parseBody.js

发布分支由master切换为release

---

lib/core/__test__/runtime/dns.hack.test.ts
lib/core/bus.ts
lib/core/config.ts
lib/core/logger/index.ts
lib/core/runtime/dns.hack.ts

feat: add dns.hack, dns.hack.test. Working on logger.

---

README.md
bin/tsw/runtime/Console.hack.js
bin/tsw/util/auto-report/logReport.js
bin/tsw/util/logger/logger.js
lib/core/bus.ts
lib/core/logger/index.ts
lib/core/runtime/console.hack.ts

style: fix eslint

---

package.json

chore(package.json): engines >= node 12

---

lib/core/__test__/runtime/console.hack.test.ts

test(console.hack): add more console.hack test

---

README.md
lib/core/__test__/runtime/console.hack.test.ts
lib/core/__test__/runtime/create-server.test.ts
lib/core/runtime/create-server.hack.ts

Add create-server.hack

---

README.md

docs(readme): add github action badge

---

.eslintrc
README.md
lib/core/__test__/logger/index.test.ts
lib/core/__test__/runtime/console.hack.test.ts
lib/core/__test__/runtime/dns.hack.test.ts
lib/core/context.ts
lib/core/logger/callInfo.ts
lib/core/logger/index.ts
lib/core/runtime/create-server.hack.ts
lib/core/runtime/dns.hack.ts
lib/core/util/isLinux.ts
tsconfig.json
typings/type.d.ts

chore: docs, lint and ts types

---

lib/core/runtime/capture/index.ts
lib/core/util/http.ts

feat: capture

---

README.md

docs: replace CI badge to Github Actions building status

---

.eslintrc
lib/core/__test__/runtime/capture/request.test.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/capture/request.ts
lib/core/runtime/capture/response.ts

Add test for request capture

---

lib/core/__test__/runtime/capture/request.test.ts
lib/core/runtime/capture/request.ts

Optimize request capture and it's test cases

---

lib/core/__test__/runtime/capture/response.test.ts
lib/core/runtime/capture/response.ts

Add response capture test cases

---

lib/core/__test__/runtime/capture/response.test.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/capture/response.ts

test: response capture test coverage 100%

---

lib/core/__test__/runtime/capture/response.test.ts
lib/core/context.ts
lib/core/logger/index.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/capture/response.ts
lib/core/runtime/capture/saz.ts
package.json
yarn.lock

Optimize capture and logger

---

README.md
lib/core/logger/index.ts

Update readme and optimize logger color

---

lib/core/__test__/runtime/capture/outgoing.test.ts
lib/core/context.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/capture/outgoing.ts
lib/core/runtime/capture/saz.ts
lib/core/runtime/create-server.hack.ts

refactor(context): rename some fileds

---

README.md
lib/core/__test__/runtime/capture/outgoing.test.ts
lib/core/bus.ts
lib/core/context.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/capture/outgoing.ts
lib/core/runtime/capture/saz.ts
lib/core/runtime/create-server.hack.ts
lib/core/runtime/dns.hack.ts

Refactor and update readme

---

bin/proxy/master.js

Use `worker.process.kill` to kill undead worker.
https://nodejs.org/api/cluster.html#cluster_worker_kill_signal_sigterm
**Checklist:**

feat: make sure undead worker will be killed (should exit)

---

bin/proxy/config.js

fix: fix wsModAct overridden by default config

---

.eslintrc
lib/core/util/isInspect.ts

fix(isinspect): allow inspecting in default port

---

.eslintrc
lib/core/runtime/capture/index.ts
lib/core/runtime/create-server.hack.ts

 Fix memory leak caused by parser on socket

---

lib/core/__test__/runtime/console.hack.test.ts
lib/core/logger/index.ts
lib/core/runtime/console.hack.ts

feat(console): hack in process.stdout and process.stderr

---

benchmark/Makefile
benchmark/originServer.js
benchmark/package-lock.json
benchmark/package.json
benchmark/run
benchmark/start.js
benchmark/startByTsw.js
benchmark/tswconfig.js

feat: add benchmark

---

lib/core/context.ts

fix(context): 修复单进程接受请求数没有增长的问题

---

yarn.lock

chore: update yarn.lock to fix security problems

---

examples/koa/yarn.lock

chore: update deps in examples

---

.github/workflows/lint-and-test-code.yml
jest.config.js
tsconfig.json

test: modify jest config, github actions, and tsconfig

---

README.md

docs(readme): Modify the payload display

---

lib/core/runtime/console.hack.ts

fix: console.hack origin parameter passed in error

---

.gitignore
package.json

chore(benchmark): improve benchmark

---

README.md

docs(readme): update quick start

---

benchmark/start/tswconfigNoReport.js

chore(benchmark): update tswconfigNoReport.js for benchmark

---

benchmark/README.md

docs(benchmark): add the doc to run benchmark

---

examples/koa/tswconfig.js

chore(example): update tswconfig.js for koa demo

---

lib/__test__/__fixtures__/error-plugin/plugin.ts

test(error-plugin): fix eslint warning

---

lib/__test__/__fixtures__/normal-plugin/plugin.ts

test(normal-plugin): fix eslint warning

---

examples/koa/README.md

docs(examples): add readme for koa demo

---

README.md

docs(readme): update doc for tswconfig.js

---

README.md

docs(readme): update table format for tswconfig.js

---

README.md

docs(readme): add link for plugin in tswconfig.js

---

lib/core/util/__test__/isInspect.test.ts

test(isinspect): completed test cases

---

examples/koa/package.json
examples/koa/yarn.lock

chore(example-koa): update dependencies of tsw and open-platform-plugin

---

lib/core/logger/index.ts

fix(logger): handle undefined of isCleanLog

---

lib/core/runtime/__test__/dns.hack.test.ts

test(dns): fix error in unit test

---

README.md

docs(readme): update readme for logLevel

---

lib/core/bus.ts

refactor(bus): reuse EVENT_LIST

---

lib/index.ts

fix(index): handle undefined of plugins

---

lib/core/runtime/create-server.hack.ts

refactor(create-server): improve for readability

---

lib/core/runtime/capture/index.ts

refactor(capture-request): improve for readability

---

lib/core/runtime/capture/__test__/index.test.ts

test(capture-request): add unit test

---

.github/workflows/publish-to-npm-alpha.yml

https://github.com/semantic-release/semantic-release/issues/1981
**Checklist:**

chore(yml): fix environments not supporting optional chaining

---

.github/workflows/publish-to-npm-alpha.yml

https://github.com/semantic-release/semantic-release/issues/1981
**Checklist:**

chore(yml): fix node environments not supporting optional chaining

---

examples/koa/package.json
examples/koa/yarn.lock

chore(example): update version of tsw

---

lib/core/runtime/capture/index.ts

chore(capture-request): improve for readability

---

lib/core/runtime/capture/index.ts

fix: 修复runtime报错

---

lib/core/logger/index.ts

fix(logger): log from console.debug don't show in inspect window

---

examples/koa/package.json
examples/koa/yarn.lock

chore(example): update version of tsw and open-platform-plugin

---

examples/koa/package.json
examples/koa/yarn.lock

chore(example-koa): update version of tsw

---

examples/https/package.json
examples/https/yarn.lock

chore(example-https): update version of tsw

---

README.md

docs(readme): add https

---

lib/core/runtime/__test__/create-server.test.ts

test(create-server): add unit test

---

.github/workflows/lint-and-test-code.yml
lib/__test__/__fixtures__/no-plugin/tswconfig.ts
lib/__test__/index.test.ts
lib/core/runtime/__test__/create-server.test.ts

test(index): add unit test

---

.github/workflows/lint-and-test-code.yml

chore(yml): revese test script

---

lib/core/runtime/__test__/create-server.test.ts

test(create-server): lint fixed

---

lib/core/runtime/__test__/dns.hack.test.ts

test(dns-hack): lint fixed

---

lib/core/runtime/capture/__test__/index.test.ts

test(capture-index): lint fixed

---

lib/core/__test__/winston.test.ts

test(winston): complement unit test

---

lib/core/logger/__test__/index.test.ts

test(logger-index): complement unit test for setLogLevel

---

lib/core/runtime/__test__/dns.hack.test.ts

test(dns-hack): add unit test

---

lib/core/runtime/__test__/dns.hack.test.ts

test(dns-hack): improve unit test

---

examples/https/README.md

docs(https-demo): improve README

---

README.md
lib/core/__test__/winston.test.ts
lib/core/winston.ts
typings/type.d.ts

fix(winston): verify the length of winston transports

---

benchmark/package-lock.json
benchmark/package.json
examples/koa/package-lock.json
examples/koa/package.json

fix: close #504

---

README.md

chore(README): 使用新版pm2时用args配置出现找不到start模块错误

---

lib/core/context.ts
lib/core/runtime/capture/index.ts
lib/core/runtime/create-server.hack.ts

fix: 上报日志使用时间戳

---

README.md

docs: 修复README文件锚点跳转和链接解析问题
